version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        hostname: app
        tty: true
        depends_on:
            - postgres
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            webservice:
                ipv4_address: ${NETWORK_APPLICATION}
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nginx:
        image: nginx:stable
        hostname: nginx
        container_name: nginx
        restart: always
        depends_on:
            - app
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            webservice:
    postgres:
        image: postgres:14
        hostname: postgres
        container_name: postgres
        restart: always
        user: postgres:postgres
        volumes:
            - ./docker/postgres/:/var/lib/postgresql/
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            webservice:
                ipv4_address: ${NETWORK_POSTGRES}
networks:
    webservice:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
