<?php

return [
    /**
     * Control if the seeder should create a user per role while seeding the data.
     */
    'create_users' => false,

    /**
     * Control if all the laratrust tables should be truncated before running the seeder.
     */
    'truncate_tables' => true,

    'roles_structure' => [
        'superadmin' => [
            'users' => 'c,r,u,d',
            'roles' => 'c,r,u,d',
            'permissions' => 'c,r,u,d',
            'dictionaries' => 'c,r,u,d',
            'dictionary_items' => 'c,r,u,d',
            'companies' => 'c,r,u,d',
            'filials' => 'c,r,u,d',
            'centres' => 'c,r,u,d',
            'departments' => 'c,r,u,d',
            'agents' => 'c,r,u,d',
            'agent_workers' => 'c,r,u,d',
            'products' => 'c,r,u,d',
            'policies' => 'c,r,u,d',
            'policy_requests' => 'r,re',
            'policy_transfers' => 'c,r,u,d',
            'product_tariffs' => 'c,r,u,d',
            'product_tariff_conditions' => 'c,r,u,d',
            'product_tariff_configurations' => 'c,r,u,d',
            'product_tariff_bonuses' => 'c,r,u,d',
            'product-tariff_risks' => 'c,r,u,d',
            'warehouses' => 'c,r,u,d',
            'warehouse_items' => 'c,r,u,d,im',
            'client_contracts' => 'c,r,u,d',
            'attempts' => 'c,r,u,d',
            'clients' => 'c,r,u,d',
            'invoices' => 'c,r,u,d',
            'payments' => 'c,r,u,d',
            'files' => 'c,r,u,d',
        ],
        'company_user' => [
            'roles' => 'r',
            'filials' => 'c,r,u,d',
            'centres' => 'c,r,u,d',
            'departments' => 'c,r,u,d',
            'agents' => 'c,r,u,d',
            'products' => 'r',
            'policies' => 'r',
            'dictionaries' => 'r',
            'client_contracts' => 'r',
            'policy_requests' => 'r,u,d,re,ap',
            'policy_transfers' => 'r,u,d,se',
            'attempts' => 'c,r,u,d',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'r',
            'clients' => 'c,r,u,d',
            'invoices' => 'c,r,u,d',
            'payments' => 'c,r,u,d',
            'files' => 'c,r,u',
        ],
        'filial_user' => [
            'roles' => 'r',
            'centres' => 'c,r,u,d',
            'departments' => 'c,r,u,d',
            'agents' => 'c,r,u,d',
            'dictionaries' => 'r',
            'policy_requests' => 'c,r,u,d,ap,se,re',
            'policy_transfers' => 'r,u,d,se,re',
            'attempts' => 'c,r,u,d',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'r',
            'clients' => 'c,r,u',
            'invoices' => 'c,r,u,d',
            'payments' => 'c,r,u,d',
            'files' => 'c,r,u',
        ],
        'branch_user' => [
            'roles' => 'r',
            'centres' => 'c,r,u,d',
            'agents' => 'c,r,u,d',
            'dictionaries' => 'r',
            'policy_requests' => 'c,r,u,d,ap,se,re',
            'policy_transfers' => 'r,u,d,se,re',
            'attempts' => 'c,r,u,d',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'r',
            'clients' => 'c,r,u',
            'invoices' => 'c,r,u,d',
            'payments' => 'c,r,u,d',
            'files' => 'c,r,u',
        ],
        'agent_yur_user' => [
            'dictionaries' => 'r',
            'agent_workers' => 'c,r,u,d',
            'policy_requests' => 'c,r,u,d,se',
            'policy_transfers' => 'r,re',
            'attempts' => 'c,r,u,d',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'r',
            'clients' => 'c,r,u',
            'invoices' => 'c,r,u,d',
            'payments' => 'c,r,u,d',
            'files' => 'c,r,u',
            'client_contracts' => 'c,r,u',
        ],
        'agent_fiz_user' => [
            'dictionaries' => 'r',
            'policy_requests' => 'c,r,u,d,se',
            'policy_transfers' => 'r,re',
            'attempts' => 'c,r,u,d',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'r',
            'clients' => 'c,r,u',
            'invoices' => 'c,r,u',
            'payments' => 'c,r,u',
            'files' => 'c,r,u',
            'client_contracts' => 'c,r,u',
        ],
        'company_agent_user' => [
            'dictionaries' => 'r',
            'policy_requests' => 'c,r,u,d,se',
            'policy_transfers' => 'r,re',
            'attempts' => 'c,r,u,d',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'r',
            'clients' => 'c,r,u',
            'invoices' => 'c,r,u',
            'payments' => 'c,r,u',
            'files' => 'c,r,u',
            'client_contracts' => 'c,r,u',
        ],
        'sub_agent_user' => [
            'dictionaries' => 'r',
            'attempts' => 'c,r,u,d',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'r',
            'clients' => 'c,r,u',
            'invoices' => 'c,r,u',
            'payments' => 'c,r,u',
            'files' => 'c,r,u',
            'client_contracts' => 'c,r,u',
        ],
        'company_axo' => [
            'dictionaries' => 'r',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'c,r,u,im',
            'policy_transfers' => 'c,r,u,d,se',
            'policy_requests' => 'r'
        ],
        'filial_axo' => [
            'dictionaries' => 'r',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'c,r,u',
            'policy_transfers' => 'c,r,u,d,se,re',
            'policy_requests' => 'r'
        ],
        'branch_axo' => [
            'dictionaries' => 'r',
            'products' => 'r',
            'policies' => 'r',
            'product_tariffs' => 'r',
            'warehouses' => 'r',
            'warehouse_items' => 'c,r,u',
            'policy_transfers' => 'c,r,u,d,se,re',
            'policy_requests' => 'r'
        ],
    ],

    'permissions_map' => [
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete',
        're' => 'receive',
        'se' => 'send',
        'ap' => 'approve',
        'co' => 'confirm',
        'im' => 'import'
    ]
];
